name: Generate

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  
  # job 1: test go module
  generate_index:
    name: Generate index html file
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout code into workspace directory
        uses: actions/checkout@v2

      - name: generate index.html
        run: python3 generate.py
      - name: Commit index file
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git fetch
          git add index.html
          git stash
          git checkout gh-pages
          git stash pop
          git add index.html
          git commit -m "Update index.html file"
          git push
